
name: Test edge_machine module

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gosetup
        run: go test state-machine/edge_machine