
name: Test modules

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@v2
      - name: gobench tools
        run: go test ./tools -test.bench -test.run
      - name: go coverage
        run: go test state-machine/edge_machine state-machine/tools state-machine/problems -coverprofile=out.cov
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: out.cov
